
Get a full info about a single package.
---
tags:
- packages
parameters:
  - name: paket_id
    in: query
    description: PKT id
    required: true
    type: string
    default: 0
definitions:
  Event:
    type: object
    properties:
      event-type:
        type: string
      timestamp:
        type: integer
      paket_user:
        type: string
      GPS:
        type: string
  Package-info:
    type: object
    properties:
      PKT-id:
        type: string
      blockchain-url:
        type: string
      collateral:
        type: integer
      custodian-id:
        type: string
      deadline-timestamp:
        type: integer
      my-role:
        type: string
      paket-url:
        type: string
      payment:
        type: integer
      recipient-id:
        type: string
      send-timestamp:
        type: integer
      status:
        type: string
      events:
        type: array
        items:
          $ref: '#/definitions/Event'
responses:
  200:
    description: a single packages
    schema:
      $ref: '#/definitions/Package-info'
